version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/apps-config"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/GMT"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "automerge"
